# 기본 설정
spring:
  profiles:
    active: dev

# 운영 환경 설정
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.c72auqk86wix.ap-northeast-2.rds.amazonaws.com:3306/todoProject?serverTimezone=Asia/Seoul
    username: admin
    password: ckawhgdmsryghl1!
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  redis:
    host: 43.200.95.124
    port: 6379
  server:
    port: 8080
  logging:
    level:
      root: INFO
      com.example: DEBUG
  jwt:
    header: Authorization
    prefix: Bearer
    tokenExpirationTime: 600
    secret: c3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwK

# 개발 환경 설정
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/runningCrew?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Jesuslove1!
  jpa:
    hibernate:
      ddl-auto: update # 테이블 자동 업데이트 (운영 환경에서는 적절히 설정 필요)
    show-sql: true # SQL 쿼리 로깅
    properties:
      hibernate:
        format_sql: true
  redis:
    host: 43.200.95.124
    port: 6379
  server:
    port: 8080 # 서버 포트 설정
  jwt:
    header: Authorization
    prefix: Bearer
    tokenExpirationTime: 600
    secret: c3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwK
